### ISSUE TITLE
1.0.1版本安装不上 

### ISSUE THREAD

**Issue by Jayshanx** [xujiaji/WanAndroid#2]
错误信息；
 Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/com.xujiaji.wanandroid-1/base.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.xujiaji.wanandroid-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.xujiaji.wanandroid-1/lib/arm, /data/app/com.xujiaji.wanandroid-1/base.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.xujiaji.wanandroid-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

**Comment by xujiaji** [comment]
尴尬了，好像是因为给app改了名字，导致安装失败。卸载老版本后，重新安装就可以了。

**Comment by xujiaji** [comment]
可能找到问题了，看来得再更新一次版本了

**Comment by Jayshanx** [comment]
还有另外一个问题，我不开新的issue了：在上拉刷新到没有更多数据之后，再下拉刷新，只会加载第一页数据，然后上拉不可用，初学者，看不出问题在哪里
但在 https://www.jianshu.com/p/b343fcff51b0 有提示到  
**注意：如果上拉结束后，下拉刷新需要再次开启上拉监听，需要使用setNewData方法填充数据。**

**Comment by xujiaji** [comment]
好的，感谢反馈

**Comment by xujiaji** [comment]
已修复，并更新版本到`1.0.2`
- App安装失败原因：dagger2的 `@BindsOptionalOf`注解需要用到` java.util.Optional`(API 24+)或者谷歌工具包Guava中的Optional，现在使用中间层`Optional`模拟谷歌Optional解决。详情请查看[Optional.java](https://github.com/xujiaji/WanAndroid/blob/master/app/src/main/java/com/google/common/base/Optional.java)
- 加载问题：`MVVMQuick`框架的 `onListRefresh` 方法没有重置加载的偏移位置，并且`Adapter`没有在更新后重置已完成加载的状态。

(￣▽￣)~*
