### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by ylmyg** [xujiaji/WanAndroid#3]
从WanAndroid跳转Tido，为什么总是显示要请先登录，我在Wan里面已经登录了，而且都在Todo找不到登录的按钮

**Comment by xujiaji** [comment]
Todo中的右下角按钮如果没有登录的情况，点击就是弹出登录对话框。
你试试退出WanAndroid账号，重新登录，再打开试试呢。突然想起我对账户登录失效没有做处理

**Comment by xujiaji** [comment]
https://github.com/hongyangAndroid/wanandroid/issues/95#issuecomment-437910967

**Comment by ylmyg** [comment]
点击右下角并没有弹出登录的对话框，而且弹出输入 todo的对话框 “列如 吃饭”....

**Comment by xujiaji** [comment]
嗯嗯，这周之内修复一下。可以试试在WanAndroid客户端重新登录后还存在这个问题吗？想看看是不是账号失效的原因

**Comment by ylmyg** [comment]
是的，重新登录以后没有了这个问题，可能是登录失效的原因，刚学习你的项目，以前没有学过MVVM模式，学习起来蛮吃力的。。

**Comment by xujiaji** [comment]
嗯，可能是因为失效这些没有清楚本地的用户信息。MVVM学起来是有些打脑壳，项目大部分都是参照的官方案例和这篇文章 https://proandroiddev.com/mvvm-architecture-viewmodel-and-livedata-part-2-di-1a6b1f96d84b

**Comment by ylmyg** [comment]
好像你给的网址是打不开的..

**Comment by xujiaji** [comment]
额... 
得翻墙，我记得有中文版的，忘了在哪了。。
可以看一下这篇文章的demo在github上，https://github.com/hazems/mvvm-sample-app
